[archive]
build_output_dir = 'FPGA Bitfiles'
archive_location = '\\us-aus-hilbuild\builds\adchurch\test-fpga-build'

[projects.fpga]
path = 'FPGA Source\FPGA Workflow Demo.lvproj'

[[build.steps]]
name = 'My Simple FPGA'
type = 'lvBuildSpec'
project = '{fpga}'
target = 'FPGA Target'
build_spec = 'Simple FPGA'

